services:
  postgresdb:
    image: postgres:15
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    restart: always
    depends_on:
      - postgresdb
    env_file:
      - .env.production
    volumes:
      - static_volume:/app/public/static
      - media_volume:/app/public/media
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/public/static
      - media_volume:/app/public/media

    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume:
