# Generated by Django 5.1.6 on 2025-02-26 06:05

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_remove_instituteadmin_user_ptr_delete_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='public/media/')),
                ('details', models.JSONField(default=list, validators=[utils.validate_details])),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
    ]
