# Generated by Django 5.1.6 on 2025-02-25 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_verified_user_phone_number_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp', models.CharField(default='882147', max_length=6)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 25, 15, 53, 3, 275983, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
