# Generated by Django 5.1.6 on 2025-02-25 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 15, 53, 47, 216380, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='915011', max_length=6),
        ),
    ]
