# Generated by Django 5.1.6 on 2025-02-25 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_otp_created_at_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 15, 54, 34, 215391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='554526', max_length=6),
        ),
    ]
