# Generated by Django 5.1.6 on 2025-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_otp_created_at_alter_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='254646', max_length=6),
        ),
    ]
