# Generated by Django 5.1.6 on 2025-02-25 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_otp_created_at_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 15, 57, 42, 973728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='629128', max_length=6),
        ),
    ]
