# Generated by Django 5.1.6 on 2025-02-25 17:23

import django.db.models.deletion
import user.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_otp_created_at_alter_otp_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='public/media/')),
                ('details', models.JSONField(default=list, validators=[user.utils.validate_details])),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTITUTE_ADMIN', 'InstituteAdmin')], default='STUDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_institute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='558428', max_length=6),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
    ]
