# Generated by Django 5.1.6 on 2025-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_instituteadmin_remove_user_phone_number_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='009724', max_length=6),
        ),
    ]
