# Generated by Django 5.1.6 on 2025-02-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteadmin',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='InstituteAdmin',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
